# Generated by Django 4.1.1 on 2022-09-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conv_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrivateKey', models.IntegerField()),
                ('Publickey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('PP', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Conv_Admin',
            fields=[
                ('conv_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Messagerie.conv_user')),
                ('FOR_NOW', models.IntegerField()),
            ],
            bases=('Messagerie.conv_user',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=5000)),
                ('ID_Conv', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('ID_Receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_Receiver', to='Messagerie.users')),
                ('ID_Reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Messagerie.message')),
                ('ID_Sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_Sender', to='Messagerie.users')),
            ],
        ),
        migrations.CreateModel(
            name='ConvToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Conv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Messagerie.conv_user')),
                ('ID_User', models.ManyToManyField(to='Messagerie.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserToConv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Messagerie.users')),
                ('ID_Conv', models.ManyToManyField(to='Messagerie.conv_admin')),
            ],
        ),
    ]
