# Generated by Django 4.1.1 on 2022-09-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conv_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Conv', models.IntegerField()),
                ('ID_Message', models.TextField(blank=True, db_column='data')),
                ('PrivateKey', models.IntegerField()),
                ('Publickey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conv_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Conv', models.IntegerField()),
                ('ID_User', models.TextField(blank=True, db_column='data')),
                ('PrivateKey', models.IntegerField()),
                ('Publickey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConvToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Conv', models.IntegerField()),
                ('ID_User', models.TextField(blank=True, db_column='data')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Message', models.IntegerField()),
                ('ID_Sender', models.IntegerField()),
                ('ID_Reply', models.IntegerField(default=0)),
                ('Text', models.CharField(max_length=5000)),
                ('ID_Conv', models.IntegerField()),
                ('Date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_User', models.IntegerField()),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('PP', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserToConv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_User', models.IntegerField()),
                ('ID_Conv', models.TextField(blank=True, db_column='data')),
            ],
        ),
    ]
