# Generated by Django 4.1.1 on 2022-10-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sessionid',
            field=models.CharField(blank=True, default='Empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='PP',
            field=models.CharField(blank=True, default='Empty', max_length=1000),
        ),
    ]
