# Generated by Django 4.1.1 on 2022-10-13 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0002_users_sessionid_alter_users_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoconv',
            name='ID_Conv',
        ),
        migrations.RemoveField(
            model_name='usertoconv',
            name='ID_User',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ID_Conv',
        ),
        migrations.AddField(
            model_name='conv_user',
            name='Messages',
            field=models.ManyToManyField(to='Messagerie.message'),
        ),
        migrations.AddField(
            model_name='conv_user',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users',
            name='Conv_User',
            field=models.ManyToManyField(to='Messagerie.conv_user'),
        ),
        migrations.DeleteModel(
            name='ConvToUser',
        ),
        migrations.DeleteModel(
            name='UserToConv',
        ),
    ]
