# Generated by Django 4.1.1 on 2022-10-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0003_remove_usertoconv_id_conv_remove_usertoconv_id_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conv_user',
            old_name='PrivateKey',
            new_name='privateKey',
        ),
        migrations.RenameField(
            model_name='conv_user',
            old_name='Publickey',
            new_name='publicKey',
        ),
    ]
