# Generated by Django 4.1.1 on 2022-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0004_rename_privatekey_conv_user_privatekey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conv_user',
            name='Name',
            field=models.CharField(blank=True, default='Unnamed', max_length=20, null=True),
        ),
    ]
