# Generated by Django 4.1.1 on 2022-10-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0005_conv_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ID_Reply',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Messagerie.message'),
        ),
    ]
