# Generated by Django 4.1.1 on 2022-10-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0006_alter_message_id_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ID_Reply',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='ID_Sender',
            new_name='Sender',
        ),
    ]
