# Generated by Django 4.1.1 on 2022-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0007_rename_id_reply_message_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username_value',
            field=models.CharField(max_length=30),
        ),
    ]
