# Generated by Django 4.1.1 on 2022-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0008_alter_users_username_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ManyToManyField(to='Messagerie.image'),
        ),
    ]
